### ISSUE TITLE
「クリックするやつ」がUnhandled rejection TypeError: Cannot read property 'surface11' of undefined

### ISSUE THREAD

**Issue by legokichi** [Narazaka/surfaces_txt2yaml#7]
[クリックするやつ](https://dl.dropboxusercontent.com/u/68134572/ghost/pages/ghostpage.html)

```
Unhandled rejection TypeError: Cannot read property 'surface11' of undefined
    at Parser.SurfacesTxt2Yaml.Parser.Parser.parse (http://localhost:8000/vendor/js/cuttlebone.js:41985:39)
    at Object.SurfacesTxt2Yaml.txt_to_data (http://localhost:8000/vendor/js/cuttlebone.js:42977:17)
    at http://localhost:8000/vendor/js/cuttlebone.js:16069:45
    at Array.forEach (native)
    at Array.forEach (http://localhost:8000/vendor/js/es6-shim.js:910:54)
    at Shell.loadSurfacesTxt (http://localhost:8000/vendor/js/cuttlebone.js:16067:33)
    at http://localhost:8000/vendor/js/cuttlebone.js:16000:46
    at tryCatcher (http://localhost:8000/vendor/js/bluebird.js:4535:31)
    at Promise._settlePromiseFromHandler (http://localhost:8000/vendor/js/bluebird.js:2670:31)
    at Promise._settlePromiseAt (http://localhost:8000/vendor/js/bluebird.js:2746:18)
    at Promise._settlePromises (http://localhost:8000/vendor/js/bluebird.js:2862:14)
    at Async._drainQueue (http://localhost:8000/vendor/js/bluebird.js:229:16)
    at Async._drainQueues (http://localhost:8000/vendor/js/bluebird.js:239:10)
    at MutationObserver.Async.drainQueues (http://localhost:8000/vendor/js/bluebird.js:67:14)
```

![スクショエビデンス](https://i.gyazo.com/3be2c983971f18875afd81fd5bddc1fd.png)

**Comment by Narazaka** [comment]
surfaces*.txtのロード順に寄るものかと(01から順に読まないとappendする対象がなくて落ちる)

**Comment by legokichi** [comment]
なるほど

**Comment by legokichi** [comment]
cat surfaces*.txtで対応
